all:

  vars:
    ansible_user: "{{ lookup('env', 'LAB_USERNAME') }}"
    ansible_password: "{{ lookup('env', 'LAB_PASSWORD') }}"
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios

  hosts:
    Router:
      ansible_host: 192.168.0.253